version: "3.7"

services:
    hexo:
        build:
            context: .
        ports:
            - "4000:4000"
        volumes:
            - ".:/home/app/laysakura.github.io"
            - /home/app/laysakura.github.io/node_modules/
